services:
  app-tgBot:
    build:
      dockerfile: ./docker/tgBot.Dockerfile
    volumes:
      - ./config/tgbot_config:/etc/tgGptBot
    networks:
      back:
        ipv4_address: 172.28.1.1

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      back:
        ipv4_address: 172.28.2.1

volumes:
  prom_data: {}

networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.0.0/16
          gateway: 172.28.0.1