services:
  app-tg-gpt-bot:
    build: ./tg-gpt-bot
    volumes:
      - ./tg-gpt-bot/config/:/etc/tg-gpt-bot/
    networks:
      - back-tier
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - back-tier
volumes:
  prom_data: 
networks:
  back-tier: