global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: app-tg-gpt-bot
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - app-tg-gpt-bot:8082
remote_write:
- url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
  basic_auth:
    username: 1025149
    password: eyJrIjoiMTYwNDUyMTJmM2EwMWExMzdjN2Y1YjE2OWEwYzNiMzNhMWViNWMxNiIsIm4iOiJza2FpZ3JvdyIsImlkIjo4NjQ4NjB9