env: "dev"
httpServer:
  address: "0.0.0.0"
  port: "8080"
  timeout: 5s
  secret: ""
db:
  host: "skygrow-pg"
  port: "5432"
  name: ""
  user: ""
  password: ""
googleAuthConfig:
  credPath: "/etc/backend-service-calendar/credentials/client_secret.json"
  tokenPath: "/etc/backend-service-calendar/credentials/token.json"
