env: "prod"
httpServer:
  address: "localhost"
  port: "8080"
  timeout: 6s
  secret: "skygrowSecretKey"
db:
  host: "localhost"
  port: "5432"
  name: "postgres"
  user: "postgres"
  password: "password"