env: "dev"
httpServer:
  address: "0.0.0.0"
  port: "8080"
  timeout: 5s
  secret: "skygrowSecretKey"
db:
  host: "skygrow-pg"
  port: "5432"
  name: "skygrowdb"
  user: "krassor"
  password: "copro123@"