env: local
httpServer:
    address: 0.0.0.0
    port: "8080"
    timeout: 5s
    secret: "123"
db:
    host: localhost
    port: "5432"
    name: postgres
    user: user
    password: password
bot:
    admins:
        - KrAssor
        - Scherk
    tgbot_apitoken: 5995322288:AAE9eClgD8cQyasmv5aywzVSaZ5yu-zcjcU
    AI:
        timeout: 300
        modelName: deepseek/deepseek-chat-v3.1:free
        aiapitoken: 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
        systemRolePromt: Ты опытный профориентолог. Проанализируй результаты теста пользователя и дай рекомендации по тому, какие профессии подойдут пользователю.
        maxTokens: 100000
        temperature: 0.5
        "n": 1
mail:
    smtpHost: smtp.rambler.ru
    smtpPort: 465
    username: proffreport@rambler.ru
    password: 71116891ProffReport@
    fromAddress: proffreport@rambler.ru
    jobBufferSize: 10
    workersCount: 3
