name: Publish to server

on:
  push:
    branches:
      - 'main'
    tags:
      - v*  # Запускается при пуше тегов, начинающихся с 'v'

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
      id-token: write
      contents: read
    # Set job outputs to values from filter step
    outputs:
      backend-service-auth: ${{ steps.filter.outputs.backend-service-auth }}
      tg-gpt-bot: ${{ steps.filter.outputs.tg-gpt-bot }}
      backend-miniaps-bot: ${{ steps.filter.outputs.backend-miniaps-bot}}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          backend-service-auth:
            - 'backend-service-auth/**'
          tg-gpt-bot:
            - 'tg-gpt-bot/**'
          backend-miniaps-bot:
            - 'backend-miniaps-bot/**'

  backend-service-auth:
    needs: changes
    name: Push Docker image to Docker Hub. backend-service-auth
    if: ${{ needs.changes.outputs.backend-service-auth == 'true' }}
    runs-on: ubuntu-latest
    steps:

     # - name: Check out the repo
     #   uses: actions/checkout@v4
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_BACKEND_SERVICE_AUTH_REPO_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image auth-service
        uses: docker/build-push-action@v6
        with:
          context: backend-service-auth
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  tg-gpt-bot:
    needs: changes
    name: Push Docker image to Docker Hub. tg-gpt-bot
    if: ${{ needs.changes.outputs.tg-gpt-bot == 'true' }}
    runs-on: ubuntu-latest
    steps:
     # - name: Check out the repo
      #  uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_TG_GPT_BOT_REPO_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image tg-gpt-bot
        uses: docker/build-push-action@v6
        with:
          context: tg-gpt-bot
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  backend-miniaps-bot:
    needs: changes
    name: Push Docker image to Docker Hub. backend-miniaps-bot
    if: ${{ needs.changes.outputs.backend-miniaps-bot == 'true' }}
    runs-on: ubuntu-latest
    steps:
     # - name: Check out the repo
      #  uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_BACKEND_MINIAPS_BOT_REPO_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image backend-miniaps-bot
        uses: docker/build-push-action@v6
        with:
          context: backend-miniaps-bot
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

 # server_update:
 #   needs: push_to_registry
 #   name: Update server buy ssh
 #   runs-on: ubuntu-latest
 #   steps:
 #     - name: Connect and run script
 #       uses: appleboy/ssh-action@master
 #       with:
 #         host: ${{ secrets.SERVER_HOST }}
 #         port: ${{ secrets.SERVER_PORT }}
 #         username: ${{ secrets.USERNAME }}
 #         password: ${{ secrets.PASSWORD }}
 #         script_stop: true
 #         script: bash deploy.sh
